# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
                    entity:
                        class: VielleCatalogBundle:User
                        property: username

    firewalls:
            # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            # activate different ways to authenticate
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /admin
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: login

        main_admin:
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            pattern:    ^/admin
            http_basic: ~
            provider: our_db_provider


            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
            Vielle\CatalogBundle\Entity\User:
                    algorithm: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
