index:
    path:     /index
    defaults: { _controller: VielleCatalogBundle:Default:index }

vielles:
    path:      /vielles
    defaults:
     _controller: VielleCatalogBundle:Vielles:catalog

subcat:
    path:      /subcat/{id}
    defaults:
        _controller: VielleCatalogBundle:Vielles:catalog
    requirements:
        sub: \d+

chant:
    path:      /chant/{id}
    defaults:
        _controller: VielleCatalogBundle:Vielles:catalog
    requirements:
        feature: \d+

decors:
    path:      /decors
    defaults:
        _controller: VielleCatalogBundle:Decors:catalog


singlevielle:
    path:      /catalog/{id}
    defaults:
        _controller: VielleCatalogBundle:Vielles:view
    requirements:
        id: \d+

singledecor:
    path:      /catalog/{id}
    defaults:
        _controller: VielleCatalogBundle:Decors:view
    requirements:
        id: \d+


vielle_catalog_addvielle:
    path:      /addvielle
    defaults:
        _controller: VielleCatalogBundle:AdminAddProduct:addvielle

vielle_catalog_adddecor:
    path:      /adddecor
    defaults:
        _controller: VielleCatalogBundle:AdminAddProduct:adddecor


vielle_catalog_edit:
    path:      /edit/{id}
    defaults:
        _controller: VielleCatalogBundle:Fiche:edit
    requirements:
        id: \d+


vielle_catalog_delete:
    path:      /delete/{id}
    defaults:
        _controller: VielleCatalogBundle:Fiche:delete
    requirements:
        id: \d+

contact:
    path:   /contact
    defaults:
        { _controller: VielleCatalogBundle:Contact:contact }

restauration:
    path:   /restauration
    defaults:
        { _controller : VielleCatalogBundle:Restauration:restauration }

luthiers:
    path:   /luthiers
    defaults:
        { _controller: VielleCatalogBundle:Luthiers:luthiers }

mentions:
    path:   /mentions
    defaults:
        { _controller: VielleCatalogBundle:Mentions:mentions }
