index:
    path:     /index
    defaults: { _controller: VielleCatalogBundle:Default:index }

vielles:
    path:      /vielles
    defaults:
     _controller: VielleCatalogBundle:Vielles:catalog

viellecat:
    path:      /subcatvielles/{id}
    defaults:
        _controller: VielleCatalogBundle:Vielles:catalog
    requirements:
        sub: \d+

decorcat:
    path:      /subcatdecor/{id}
    defaults:
        _controller: VielleCatalogBundle:Decors:catalog
    requirements:
        sub: \d+

chant:
    path:      /chant/{id}
    defaults:
        _controller: VielleCatalogBundle:Vielles:catalog
    requirements:
        feature: \d+

decors:
    path:      /decors
    defaults:
        _controller: VielleCatalogBundle:Decors:catalog


singlevielle:
    path:      /catalog/{id}
    defaults:
        _controller: VielleCatalogBundle:Vielles:view
    requirements:
        id: \d+

singledecor:
    path:      /catalog/{id}
    defaults:
        _controller: VielleCatalogBundle:Decors:view
    requirements:
        id: \d+

admin_index:
    path:   /admin/index
    defaults:
        _controller: VielleCatalogBundle:AdminIndex:index

vielle_catalog_addvielle:
    path:      /admin/addvielle
    defaults:
        _controller: VielleCatalogBundle:AdminAddProduct:addvielle

vielle_catalog_adddecor:
    path:      /admin/adddecor
    defaults:
        _controller: VielleCatalogBundle:AdminAddProduct:adddecor


vielle_catalog_edit:
    path:      /admin/editvielle/{id}
    defaults:
        _controller: VielleCatalogBundle:AdminEditProduct:editvielle
    requirements:
        id: \d+


vielle_catalog_delete:
    path:      /admin/delete/{id}
    defaults:
        _controller: VielleCatalogBundle:AdminDeleteProduct:deleteitem
    requirements:
        id: \d+

contact:
    path:   /contact
    defaults:
        { _controller: VielleCatalogBundle:Contact:contact }

restauration:
    path:   /restauration
    defaults:
        { _controller : VielleCatalogBundle:Restauration:restauration }

luthiers:
    path:   /luthiers
    defaults:
        { _controller: VielleCatalogBundle:Luthiers:luthiers }

mentions:
    path:   /mentions
    defaults:
        { _controller: VielleCatalogBundle:Mentions:mentions }
