services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: true

#    vielle_catalog.example:
#        class: Vielle\CatalogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    vielle_catalog.message:
        class: Vielle\CatalogBundle\Services\Message
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mailer"

    vielle_catalog.uploader:
        class: Vielle\CatalogBundle\Services\Uploader
        arguments:
            $targetDir: "%products_directory%"
