services:
    _defaults:
        autowire: false
        autoconfigure: true
        public: true

#    vielle_catalog.example:
#        class: Vielle\CatalogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    vielle_catalog.message:
        class: Vielle\CatalogBundle\Services\Message
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@mailer"

    vielle_catalog.uploader:
        class: Vielle\CatalogBundle\Service\Uploader
        arguments:
            $targetDir: "%products_directory%"

    vielle_catalog.vielleservice:
            class: Vielle\CatalogBundle\Service\VielleService
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@vielle_catalog.uploader"
                - "@form.factory"
                - "@service_container"

    vielle_catalog.seoservice:
        class: Vielle\CatalogBundle\Service\SeoService
        arguments:
            - "@sonata.seo.page"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - '@request_stack'

