<?php

namespace Vielle\CatalogBundle\Repository;

/**
 * FeatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureRepository extends \Doctrine\ORM\EntityRepository
{
	public function findBySubcategory($subcatId)
	{
		return $this
			->createQueryBuilder('f')
			->where('f.subcategory IN (:subcategory)')
			->setParameter('subcategory', $subcatId)
			->getQuery()
			->getResult()
			;
	}
}
